name: Build Executables

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: 'Select platform to build'
        required: true
        options:
          - windows
          - macos
          - linux

jobs:
  build-windows:
    if: github.event.inputs.platform == 'windows'
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          pyinstaller_ver: '==6.10.0'
          spec: 'snap_sweeper.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Snap Sweeper'

  build-macos:
    if: github.event.inputs.platform == 'macos'
    runs-on: macos-latest
    steps:
      - name: Install LLVM and LibOMP
        run: |
          brew install llvm libomp gcc@14
          echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH
          echo "CXX=g++-14" >> $GITHUB_ENV
          echo "CC=gcc-14" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          pyinstaller_ver: '==6.10.0'
          spec: 'snap_sweeper.spec'
          requirements: 'requirements.txt'

  build-linux:
    if: github.event.inputs.platform == 'linux'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          pyinstaller_ver: '==6.10.0'
          spec: 'snap_sweeper.spec'
          requirements: 'requirements.txt'