name: Build Windows Executable

on:
  workflow_dispatch:

env:
  FILE_NAME: 'Snap_Sweeper_Windows'

jobs:
  build-and-upload-executable:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          pyinstaller_ver: '==6.10.0'
          spec: 'snap_sweeper.spec'
          requirements: 'requirements.txt'

      - name: Zip Executable
        run: |
          Compress-Archive -Path "dist\Snap Sweeper" -DestinationPath "${{ env.FILE_NAME }}.zip" -Force

      - name: Auth to GCP
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Upload Executable to GCS
        id: 'upload-files'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: "./${{ env.FILE_NAME }}.zip"
          destination: 'snap-sweeper-binary'
